apiVersion: v1
kind: ConfigMap
metadata:
  name: cce-configmap
  namespace: crypto-currency-exchange
data:

  DEBUG: 'False'
  # Replace The Database Host, I deployed postgres via CNPG 
  DATABASE_HOST: 'cnpg-cluster-rw.database.svc.cluster.local'
  DATABASE_PORT: '5432'
  HAS_MIGRATION: '1'
  ALLOWED_HOSTS: crypto-currency-exchange.example.com